### ISSUE TITLE
在自己的数据集上fine tuning

### ISSUE THREAD

**Issue by YINGPENGZH** [beyondguo/genius#5]
您好，在git上没有看到fine tune相关代码，请问在自己的数据集上fine tune使用预训练的代码就可以了吗？

**Comment by beyondguo** [comment]
您好，如果针对分类任务数据增强的finetune，参考https://github.com/beyondguo/genius/blob/master/augmentation_clf/genius_finetune.py

如果是general的finetune，可以直接参考预训练代码。

**Comment by YINGPENGZH** [comment]
> 您好，如果针对分类任务数据增强的finetune，参考https://github.com/beyondguo/genius/blob/master/augmentation_clf/genius_finetune.py
> 
> 如果是general的finetune，可以直接参考预训练代码。

您好，我是要做单纯的生成任务，想再问一下，输入数据的格式是什么呢？有样例数据吗？

**Comment by taishan1994** [comment]
> > 您好，如果针对分类任务数据增强的finetune，参考https://github.com/beyondguo/genius/blob/master/augmentation_clf/genius_finetune.py
> > 如果是general的finetune，可以直接参考预训练代码。
> 
> 您好，我是要做单纯的生成任务，想再问一下，输入数据的格式是什么呢？有样例数据吗？

你可以参考这里：https://github.com/taishan1994/genius_for_your_data
