### ISSUE TITLE
genius-large-k2t model not found

### ISSUE THREAD

**Issue by chenkaiustc** [beyondguo/genius#7]
Where can I try the k2t model? Thanks!

**Comment by beyondguo** [comment]
Hi, the K2T model is under maintenance, will be released in a few days. 
Currently, we suggest directly use the `genius-large` model for generation, which also support keywords as input, by concatenating keywords/phrases with `<mask>` tokens.

For example:
- input: `<mask> have fun  <mask> Sunday  <mask> beach <mask>`
- genius-large: `Come and have fun on a Sunday at the beach. There will be food, drinks, games, and more. ...`

**Comment by chenkaiustc** [comment]
Thanks very much. Look forward to it :)

**Comment by beyondguo** [comment]
Hi @chenkaiustc , the [k2t model](https://huggingface.co/beyond/genius-large-k2t) is available now! You can have a try.
However, I still suggest using the genius-large for generation, which uses more training data and is more flexible at controlling.
