### ISSUE TITLE
中文语料的构成？

### ISSUE THREAD

**Issue by ScottishFold007** [beyondguo/genius#9]
您好，您的项目非常赞！我想了解下，您的中文数据的构成如何？我想在您所提供的语料的基础上再增加一些作文和小说的语料，不知道是否和您现有的语料有重合，谢谢~

**Comment by beyondguo** [comment]
您好，中文训练预料已经上传到huggingface，可以再这里了解详情:  https://huggingface.co/datasets/beyond/chinese_clean_passages_80m

这个数据集包含了8千万段落，我训练时由于时间因素只采样了1000万。这里面主要是新闻，所以您继续在作文和小说上训练肯定是有效的。

**Comment by ScottishFold007** [comment]
> 您好，中文训练预料已经上传到huggingface，可以再这里了解详情: https://huggingface.co/datasets/beyond/chinese_clean_passages_80m
> 
> 这个数据集包含了8千万段落，我训练时由于时间因素只采样了1000万。这里面主要是新闻，所以您继续在作文和小说上训练肯定是有效的。

谢谢您的细心解答，我试试扩增语料+训练大模型的效果，到时有结果了跟你同步下~

**Comment by beyondguo** [comment]
欢迎啊，到时候您可以把模型分享出来，我可以在github上加一个链接给大家尝试。
